version: 0.2

phases:
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 sync dist/ "s3://${BUCKET_NAME}" --acl=public-read --delete
      - aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths /\*
